# Generated by Django 4.1.5 on 2024-02-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
